version: '3.4'

services:
  db:
    image: postgres:alpine
    networks:
      - default
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

  jpsalertcrud:
    image: jpsalertcrud
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - default
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app/

networks:
  default:
volumes:
  postgres-db: